msg = "My name is Akkharaphong"
msg2 = "I'm from Thailand"
msg3 = "jkajdfkjd;afjkasdjfkl;xxxxxxxxxxxxx"
msg = "My name is Akkharaphong"
msg2 = "I'm from Thailand"
msg3 = "jkajdfkjd;afjkasdjfkl;xxxxxxxxxxxxx"
msg = "My name is Akkharaphong"
msg2 = "I'm from Thailand"
msg3 = "jkajdfkjd;afjkasdjfkl;xxxxxxxxxxxxx"
msg = "My name is Akkharaphong"
msg2 = "I'm from Thailand"
msg3 = "jkajdfkjd;afjkasdjfkl;xxxxxxxxxxxxx"
print(msg+msg2+msg3)
